project:
  type: website

website:
  title: "icode"
  navbar:
    left:
      - href: index.qmd
        text: "Начини с нуля"
      - href: icode/ican.qmd
        text: Я умею!
      - href: tasks.qmd
        text: "Банк заданий"
      - icode/about.qmd

  sidebar:
    - title: "Банк заданий"
      style: "docked"
      background: light
      contents:
        - tasks.qmd
        - icode/hello.qmd

format:
  html:
    theme: bootswatch
    css: styles.css
    toc: true



