---
filters:
  - pyodide
---

# Привет😺. Много приветов.

## Самая простая программа в мире

Классическим примером короткой программы является "Привет, мир!".
Это программа из одной строки, которая печатает на экран всего одно предложение.
На Python эта программа выглядит следующим образом:

```python 
print("Hello, world!")

```

В программе используется строка `"Hello, world!"` и встроенная функция `print()`. 
Проще программы и не придумаешь! 

На сайте [Rosetta Code](https://rosettacode.org/wiki/Hello_world/Text)
приведены примеры этой же программы на других языках программирования.
Сравните, на чем проще написать такую программу, на Python 
или другом языке программирования? В чем, на ваш взгляд,
основные отличия в синтаксисе разных языков программирования? 

## Интерактивные возможности 

Этот и другие примеры кода вы можете не только посмотреть, 
но и запустить прямо на нашем сайте.

После загрузки страницы необходимо подождать, когда появится кнопка `Run Code`,
затем нажать ее, после чего вы сразу увидите результат выполнения программы.
В нашем случае это будет напечатанное на экране приветствие.

```{pyodide-python} 
print("Hello, world!")

```

Вы также можете изменить код программы, например, вместо
`"Hello, world!"` написать `"Привет, мир!"` 
или передать привет пользователям на других языках.

Ранее подобные интерактивные возможности широко использовалась, 
например, [в базовом учебнике для языка Rust](https://doc.rust-lang.ru/book/ch01-02-hello-world.html#%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BC%D0%B8%D1%8F-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B-%D0%BD%D0%B0-rust),
но сейчас стали доступны для языка Python благодаря проекту [pyodide](https://pyodide.org/en/stable/).
Наш сайт один из первых, где вы можете запускать код на Python прямо на странице.    

## А теперь много приветов!

В новом [языке программирования Hare](https://harelang.org/)
один из первых примеров – это приветствия на нескольких 
иностранных языках. Код на Hare выглядит следующим образом:

```hare
use fmt;

export fn main() void = {
	const greetings = [
		"Hello, world!",
		"¡Hola Mundo!",
		"Γειά σου Κόσμε!",
		"Привіт, світ!",
		"こんにちは世界！",
	];
	for (let i = 0z; i < len(greetings); i += 1) {
		fmt::println(greetings[i])!;
	};
};
```

::: {.callout-tip}

## Вопросы и задания

1. Как такую программу написать на Python?
2. Какие иностранные языки для приветствия вы будете использовать?
3. Откуда взять официальные обозначения для этих языков?
4. Какая структура данных будет использоваться для хранения приветствий?
5. Как пользователь сможет выбрать язык, на котором программа напечатает приветствие?
6. На скольки языках могут поздороваться с вами студенты МГИМО?

:::